name: Check Backend Directory Changes

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees monitorear
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files in backend directory
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**  # Monitorea todos los archivos dentro del directorio backend

      - name: Run job if changes detected
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "Changes detected in the backend directory."