name: Check Backend Directory Changes

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees monitorear
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files in backend directory 
        id: changed-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: backend/**  # Monitorea todos los archivos dentro del directorio backend

      - name: Cambios en el backend
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "Ejecutando el dockerfile de Backend"


      - name: Get changed files in frontend directory

        id: changed-frontend
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: frontend/**  # Monitorea todos los archivos dentro del directorio backend

      - name: Cambios en el Frontend
        if: steps.changed-frontend.outputs.any_changed == 'true'
        run: echo "Ejecutando el dockerfile de Frontend"

