name: Build and Test Images

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Check changes in backend directory
        id: changed-backend-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: backend/**

      - name: Build the Backend Image
        if: steps.changed-backend-files.outputs.any_changed == 'true'
        run: |
          docker build ./backend --file ./backend/Dockerfile 
          echo "Funciono el backend"

      - name: Check changes in frontend directory
        id: changed-frontend-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: frontend/**

      - name: Build the Frontend Image
        if: steps.changed-frontend-files.outputs.any_changed == 'true'
        run: |
          docker build ./frontend --file ./frontend/Dockerfile 
          echo "Funciono el frontend"
