name: Build and Test Images

on:
  push:
    branches:
      - 'main'
      - 'master'


jobs:
  check_backend_changes:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in backend directory
        id: changed-backend-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: backend/**
    
        
      - name: Build the Backend Image
        if: steps.changed-backend-files.outputs.any_changed == 'true'

        run: |
          docker build ./backend --file ./backend/Dockerfile 
          echo "Imagen del Backend construida"

  check_frontend_changes:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in frontend directory
        id: changed-frontend-files
        uses: tj-actions/changed-files@v45 
        with:
          files: frontend/**
         
      - name: Build the Frontend Image
        run: |
          if: steps.changed-frontend-files.outputs.any_changed == 'true'
          docker build ./frontend --file ./frontend/Dockerfile 
          echo "Imagen del Frontend construida"

  build_images:
    runs-on: ubuntu-latest

    steps:
      - name: Notification
        run: | 
          echo "Proceso ejecutado correctamente"
