name: Build and Test Images

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in backend directory
        id: changed-backend-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: backend/**

      - name: Check changes in frontend directory
        id: changed-frontend-files
        uses: tj-actions/changed-files@v45 
        with:
          files: frontend/**

  run_tests:
    runs-on: ubuntu-latest
    needs: check_changes  # Asegura que el job de verificación de cambios se ejecute antes de este job

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd backend
          ls
          pip install -r requirements.txt
          pip install pytest
          pip install coverage
              
      - name: Run Backend tests
        run: |
          cd backend
          #python manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Especifica la versión de Node.js que necesitas

      - name: Install pnpm
        run: |
          cd frontend 
          npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend 
          pnpm install

      - name: Run tests
        run: |
          cd frontend 
          #pnpm vitest  # Asegúrate de que este comando esté definido en tu package.json
  
    build_images:
      runs-on: ubuntu-latest
      needs: run_tests

      steps:
      - name: Build the Backend Image
        if: steps.changed-backend-files.outputs.any_changed == 'true'
        run: |
          docker build ./backend --file ./backend/Dockerfile 
          echo "Imagen del Backend contruida"



      - name: Build the Frontend Image
        if: steps.changed-frontend-files.outputs.any_changed == 'true'
        run: |
          docker build ./frontend --file ./frontend/Dockerfile 
          echo "Imagen del Frontend contruida"


      - name: Success
        run: | 
          echo "Proceso ejecutado correctamente"

    
