name: Check Changes and build images

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in backend folder
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^backend/'; then
            echo "Changes detected in the backend/ folder";
          fi

      - name: Check for changes in frontend folder
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^frontend/'; then
            echo "Changes detected in the frontend/ folder";
          fi
