name: Build and Test Images

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in backend directory
        id: changed-backend-files
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**

      - name: Check changes in frontend directory
        id: changed-frontend-files
        uses: tj-actions/changed-files@v45
        with:
          files: frontend/**

  run_tests:
    runs-on: ubuntu-latest
    needs: check_changes

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Backend dependencies
        if: ${{ steps.changed-backend-files.outputs.files != '' }}
        run: |
          cd backend
       #   pip install -r requirements.txt
       #   pip install pytest coverage

      - name: Run Backend tests
        if: ${{ steps.changed-backend-files.outputs.files != '' }}
        run: |
          cd backend
        #  python manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm for Frontend
        if: ${{ steps.changed-frontend-files.outputs.files != '' }}
        run: |
       #   npm install -g pnpm

      - name: Install Frontend dependencies
        if: ${{ steps.changed-frontend-files.outputs.files != '' }}
        run: |
          cd frontend
       #   pnpm install

      - name: Run Frontend tests
        if: ${{ steps.changed-frontend-files.outputs.files != '' }}
        run: |
          cd frontend
       #   pnpm vitest

  build_images:
    runs-on: ubuntu-latest
    needs: [run_tests, check_changes]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Backend Image
        if: ${{ steps.changed-backend-files.outputs.files != '' }}
        run: |
          docker build -t backend-image:latest ./backend -f ./backend/Dockerfile
          echo "Imagen del Backend construida"

      - name: Build the Frontend Image
        if: ${{ steps.changed-frontend-files.outputs.files != '' }}
        run: |
          docker build -t frontend-image:latest ./frontend -f ./frontend/Dockerfile
          echo "Imagen del Frontend construida"

      - name: Success
        run: echo "Proceso ejecutado correctamente"
