name: Build and Test Images

on:
  push:
    branches:
      - 'main'
      - 'master'


jobs:
  check_backend_changes:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]
    
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in backend directory
        id: changed-backend-files
        uses: tj-actions/changed-files@v45  ## verificar si cambio algun directorio
        with:
          files: backend/**

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}      

      - name: Install dependencies
        run: |
          cd backend
          ls
          pip install pytest
          pip install coverage
        #  pip install -r requirements.txt

                
      - name: Run Backend tests
        run: |
          cd backend
        # python manage.py test
        
      - name: Build the Backend Image
        run: |
          docker build ./backend --file ./backend/Dockerfile 
          echo "Imagen del Backend construida"

  check_frontend_changes:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changes in frontend directory
        id: changed-frontend-files
        uses: tj-actions/changed-files@v45 
        with:
          files: frontend/**

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend 
        #  pnpm install

      - name: Run tests
        run: |
          cd frontend 
        # pnpm vitest  # Asegúrate de que este comando esté definido en tu package.json
          
      - name: Build the Frontend Image
        run: |
          docker build ./frontend --file ./frontend/Dockerfile 
          echo "Imagen del Frontend construida"

  build_images:
    runs-on: ubuntu-latest
    needs: [check_backend_changes, check_frontend_changes]

    steps:
      - name: Notification
        run: | 
          echo "Proceso ejecutado correctamente"
