name: Notify User on Workflow Completion

on:
  push:
    branches:
      - main

jobs:
  notify_user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow Notification"
          body: "The workflow has completed successfully."
          to: alvaro@grancaribe.gca.tur.cu
          from: "Your Name <alvaro.eng.98@gmail.com>"